# Generated by Django 3.2.25 on 2025-08-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250520_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='local',
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
